### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JianAtSeer** [anfoss/PCprophet#11]
**Describe the bug**
The setup.py for installation seems not correct, it is complaining that there are some files are missing.

e.g.
generate_feature.py
-- i see a different file is available called generate_feature_v2.py in the PCProphet directory

parse_go.py
--I see a slightly different file name called parse_GO.py (note the capital letter)

**Extract of sample ids file and protein matrix used**
Provide example of sample_ids.txt and a sample of the input matrix used.

**To Reproduce**
trying to install using pip install after cloning the repo

**Screenshots**
Provide screenshot of the terminal error message

**Desktop (please complete the following information):**
 - OS: linux
 - Python version: 3.7
- Dependencies and version number

**Additional context**

**Comment by anfoss** [comment]
Will work on a fix as we changed quite a lot since the last setup.py update.

In the meantime you can just clone the repo to get a working copy of PCprophet
git-lfs clone https://github.com/anfoss/PCprophet PCprophet
