### ISSUE TITLE
help with error 

### ISSUE THREAD

**Issue by smdb21** [anfoss/PCprophet#2]
Hi:
We are running our data which consist on 2 replicates of a fractionation of 119 fractions each, with NSAF values for each protein in each fraction.
When running it, I got some error that seemed to be related to the parallel processing, so I disabled it by using -mult False. Then, the process looked to pass the point it was failing before, but now I get another error.
Could you please help me with it?
```
python main.py -sid "path\Human\sample_ids.txt" -db "path\Human\coreComplexes_human.txt" -is_ppi False -mult False
mapping path\Human\Beta_cell_PCP_NSAF_Human.pcprophet.tsv to path\Human\coreComplexes_human.txt
Generating hypothesis for path\Human\Beta_cell_PCP_NSAF_Human.pcprophet.tsv
combining hypothesis and corum for ./tmp\Beta_cell_PCP_NSAF_Human.pcprophet
calculating features for ./tmp\Beta_cell_PCP_NSAF_Human.pcprophet\cmplx_combined.txt
mapping path\Human\Beta_cell_PCP_2_NSAF_Human.pcprophet.tsv to path\Human\coreComplexes_human.txt
Generating hypothesis for path\Human\Beta_cell_PCP_2_NSAF_Human.pcprophet.tsv
combining hypothesis and corum for ./tmp\Beta_cell_PCP_2_NSAF_Human.pcprophet
calculating features for ./tmp\Beta_cell_PCP_2_NSAF_Human.pcprophet\cmplx_combined.txt
Beta_cell_PCP_2_NSAF_Human.pcprophet condition1_2
Not enough reported for FDR estimation, using GMM model
Traceback (most recent call last):
  File "main.py", line 247, in <module>
    main()
  File "main.py", line 222, in main
    collapse.runner(
  File "mypath\PCprophet\collapse.py", line 501, in runner
    exp.calc_fdr(fdr)
  File "mypath\PCprophet\collapse.py", line 246, in calc_fdr
    hyp, fdr = go_fdr.fdr_from_GO(
  File "mypath\PCprophet\go_fdr.py", line 182, in fdr_from_GO
    predicted = calc_pdf(go_hypo)
  File "mypath\PCprophet\go_fdr.py", line 91, in calc_pdf
    pred_ = clf.fit(X).predict(X.reshape(-1, 1)).reshape(-1, 1)
  File "mypath2\Anaconda3\envs\PCProphet\lib\site-packages\sklearn\mixture\_base.py", line 193, in fit
    self.fit_predict(X, y)
  File "mypath2\Anaconda3\envs\PCProphet\lib\site-packages\sklearn\mixture\_base.py", line 220, in fit_predict
    X = _check_X(X, self.n_components, ensure_min_samples=2)
  File "mypath2\Anaconda3\envs\PCProphet\lib\site-packages\sklearn\mixture\_base.py", line 52, in _check_X
    X = check_array(X, dtype=[np.float64, np.float32],
  File "mypath2\Anaconda3\envs\PCProphet\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "mypath2\Anaconda3\envs\PCProphet\lib\site-packages\sklearn\utils\validation.py", line 650, in check_array
    raise ValueError("Found array with %d sample(s) (shape=%s) while a"
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 2 is required.
```

Let me know if you need more information.
Thank you!

**Comment by anfoss** [comment]
Hi,
The GMM model is a fall-back option for when there no reported complexes (from the provided db) in the datasets. Is that intended/expected?  
The error is triggered from the lack of GO term scores (i.e empty array). Can you double check that in
/tmp\Beta_cell_PCP_2_NSAF_Human.pcprophet\mp_feat_norm.txt the columns 

SC_CC | SC_MF | SC_BP | TOTS
-- | -- | -- | --

Have non 0 values?

Additionally can you provide the first few lines of your input data? Based on the errors it seems to me like a simple identifier issue.

**Comment by smartinez-yatiribio** [comment]
Hi:
Thank you very much for your response.
I double-checked and the file /tmp\Beta_cell_PCP_2_NSAF_Human.pcprophet\mp_feat_norm.txt has all 0 values in these columns.
I attach here the first 20 lines of one of the input files. Let me know if there is something wrong on it.

[Beta_cell_PCP_2_NSAF_Human.pcprophet_small.txt](https://github.com/anfoss/PCprophet/files/6238646/Beta_cell_PCP_2_NSAF_Human.pcprophet_small.txt)

Answering your question about whether it is expected...it is not...although we have had some very poor results with other software. We suspect that the NSAF values are not suitable for this type of analysis, and so we may want to extract MS1 quant values for this. Do you agree with this?
Thank you again!
Salva.

**Comment by smdb21** [comment]
Hi:
Thank you very much for your response.
I double-checked and the file /tmp\Beta_cell_PCP_2_NSAF_Human.pcprophet\mp_feat_norm.txt has all 0 values in these columns.
I attach here the first 20 lines of one of the input files. Let me know if there is something wrong on it.

[Beta_cell_PCP_2_NSAF_Human.pcprophet_small.txt](https://github.com/anfoss/PCprophet/files/6238661/Beta_cell_PCP_2_NSAF_Human.pcprophet_small.txt)

Answering your question about whether it is expected...it is not...although we have had some very poor results with other software. We suspect that the NSAF values are not suitable for this type of analysis, and so we may want to extract MS1 quant values for this. Do you agree with this?
Thank you again!
Salva.

**Comment by anfoss** [comment]
PCprophet will perform better on MS1 or MS2 XIC, but NSAIF is supported too.
The provided file has GN swapped with ID. You can double check in [this](https://github.com/anfoss/PCprophet/blob/aa1f7e03600561a38889806f0f9c600d83bb6a5b/test/test_frac.txt) test file for the correct format and headers. A quick way to check if the mapping is fine (without having to wait to fully generate all features) is to run PCprophet and check this file (which is the first thing generated).
/tmp\Beta_cell_PCP_2_NSAF_Human.pcprophet\ann_cmplx.txt
It should have reported complexes from the database used.  

On the side note, I see some non-mammals entry in your file, you might want to test whether providing an interaction network human + bacteria would be better

**Comment by smdb21** [comment]
Thank you very much for looking into the data. It was my mistake. After fixing it, I tried yesterday and it definitely runs further, however it failed 

later. Here is what I get:
```
(PCProphet) path\PCprophet>python main.py -sid "path\Human\sample_ids.txt" -db "path\Human\coreComplexes_human.txt" -is_ppi False -mult True
mapping path\Human\Beta_cell_PCP_2_NSAF_Human.pcprophet.tsv to path\Human\coreComplexes_human.txt
mapping path\Human\Beta_cell_PCP_NSAF_Human.pcprophet.tsv to path\Human\coreComplexes_human.txt
Generating hypothesis for path\Human\Beta_cell_PCP_NSAF_Human.pcprophet.tsv
Generating hypothesis for path\Human\Beta_cell_PCP_2_NSAF_Human.pcprophet.tsv
combining hypothesis and corum for ./tmp\Beta_cell_PCP_NSAF_Human.pcprophet
combining hypothesis and corum for ./tmp\Beta_cell_PCP_2_NSAF_Human.pcprophet
calculating features for ./tmp\Beta_cell_PCP_NSAF_Human.pcprophet\cmplx_combined.txt
calculating features for ./tmp\Beta_cell_PCP_2_NSAF_Human.pcprophet\cmplx_combined.txt
Traceback (most recent call last):
  File "main.py", line 247, in <module>
    main()
  File "main.py", line 217, in main
    p.map(preproc_conf, files)
  File "path2\Anaconda3\envs\PCProphet\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "path2\Anaconda3\envs\PCProphet\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "path2\Anaconda3\envs\PCProphet\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "path2\Anaconda3\envs\PCProphet\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "main.py", line 201, in preprocessing
    generate_features.runner(
  File "path3\PCprophet\generate_features.py", line 381, in runner
    wr, pks = mp_cmplx(filename=cmplx_comb, goobj=go_tree, gaf=gaf)
  File "path3\PCprophet\generate_features.py", line 364, in mp_cmplx
    feat_row, peaks = gen_feat(cmplx, goobj, gaf)
  File "path3\PCprophet\generate_features.py", line 332, in gen_feat
    cmplx.pairwise()
  File "path3\PCprophet\generate_features.py", line 169, in pairwise
    self.calc_corr(pairs)
  File "path2\Anaconda3\envs\PCProphet\lib\site-packages\numpy\testing\_private\utils.py", line 2300, in new_func
    with self:
  File "C:\Users\salvador\Anaconda3\envs\PCProphet\lib\site-packages\numpy\testing\_private\utils.py", line 2204, in __enter__
    raise RuntimeError("cannot enter suppress_warnings twice.")
RuntimeError: cannot enter suppress_warnings twice.
```

Here I put the files in the tmp folder as they have been generated:
https://www.dropbox.com/s/8ivwoxum3yr8hds/tmp.zip?dl=0

Thank you again for your help!
Salva.

**Comment by anfoss** [comment]
This sounds like a pesky numpy error. Will have a look and eventually raise an issue. Running without multiprocessing should be fine.

**Comment by smdb21** [comment]
Just to let you know that it worked, disabling the mult flag. thanks!
Do you want me to give you the output errors using -v True?

**Comment by anfoss** [comment]
If you can send the logs via email would be great. As this issue is solved, I will close it for now. Don't hesitate to reach out for further questions or issues
