### ISSUE TITLE
[BUG] Warning from pandas when analysing test data

### ISSUE THREAD

**Issue by s-andrews** [anfoss/PCprophet#3]
**Describe the bug**
Running the test data on our cluster generates the following warning

```
/bi/apps/pcprophet/1.1/PCprophet/PCprophet/collapse.py:325: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["ID"] = "cmplx__" + str(count)
Creating complex level report
``` 

**Extract of sample ids file and protein matrix used**
This was using the test data distributed with the program.

**To Reproduce**
```python3 main.py -sid test/test_ids.txt -is_ppi False -db coreComplexes.txt```

**Screenshots**
```
/bi/apps/pcprophet/1.1/PCprophet/PCprophet/collapse.py:325: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["ID"] = "cmplx__" + str(count)

```

**Desktop (please complete the following information):**
 - OS: Linux CentOS 7
 - Python version: 3.7.3
- Dependencies and version number
```
>>> numpy.__version__
'1.20.2'
>>> pandas.__version__
'1.2.4'
```

**Additional context**

**Comment by anfoss** [comment]
This is a warning that can be safely ignored as it is dependent on Pandas in place operations.
