### ISSUE TITLE
[BUG] Broken shebang line on main.py

### ISSUE THREAD

**Issue by s-andrews** [anfoss/PCprophet#4]
**Describe the bug**
The ```main.py``` file has a space between the ```#``` and the ```!``` which means that bash won't read it correctly and you can't execute it directly.

**To Reproduce**
```
chmod 755 main.py
./main.py
```

**Additional context**

Just change it to:

```#!/usr/bin/env python3```

**Comment by chenli-bioinfo** [comment]
Dear Simon, thank you for your advice. We have accordingly deleted the space between "#" and "!" in the shebang line. We shall now close this issue.
