### ISSUE TITLE
[BUG] Numpy crash when analysing data

### ISSUE THREAD

**Issue by s-andrews** [anfoss/PCprophet#5]
**Describe the bug**
During the feature calculation we get a crash from an internal routine in numpy relating to the suppression of warnings.  Processing of the data stops at this point.

**Extract of sample ids file and protein matrix used**
Sorry, this isn't my data so I can't immediately share this, I've just had it reported to me.  I can try to get the actual data if it helps with the problem.

**To Reproduce**
[Copied from screenshot! Sorry if there are typos]
```python3 main.py -sid Input/sample_ids.txt -db coreComplexes.txt -output Output/ -cal Input/calibration_table.txt```
[pcprophet.out.txt](https://github.com/anfoss/PCprophet/files/6338385/pcprophet.out.txt)

**Screenshots**
[pcprophet.out.txt](https://github.com/anfoss/PCprophet/files/6338385/pcprophet.out.txt)

**Desktop (please complete the following information):**
 - OS: CentOS7
 - Python version: 3.7.3
- Dependencies and version number

```>>> numpy.__version__
'1.20.2'


**Additional context**
Don't know[ if this is related](https://github.com/pytest-dev/pytest/issues/4617).  Same error but seems long enough ago that it should have been fixed in numpy.  I had a look at the stack trace but couldn't make sense of it.

**Comment by anfoss** [comment]
Seems the same error related to a previously raised issue [here](https://github.com/anfoss/PCprophet/issues/2). I am currently looking into that. There are some conflicts between numpy suppression or errors and multiprocessing using Pool.
I have the same solutions (atm) as in the previous answer,
1. Use PCprophet with the -mult False flag -> no multiprocessing
2. Use PCprophet with the -v False flag -> no verbose. This will print a lot of warnings to the stdout but is mostly numpy complaining of zeroes in the data when we do window-wide calculations so it is expected and nothing to be concerned.

You can try either of them and let me know if it works?

**Comment by s-andrews** [comment]
Running with the -mult False flag allowed this to complete (there was a separate error but I'll put in another report for that).  Thanks!

**Comment by anfoss** [comment]
Great, will close this now then
