### ISSUE TITLE
Missing comma in main.py line 126

### ISSUE THREAD

**Issue by GregStacey** [anfoss/PCprophet#7]
There appears to be a missing comma in main.py on line 126.

Cloning the newest version and running `python3 main.py -sid test/test_ids.txt -is_ppi False -db coreComplexes.txt` gives the following error.
```
python3 main.py -sid test/test_ids.txt -is_ppi False -db coreComplexes.txt
  File "main.py", line 136
    parser.add_argument("-w", dest="weight_pred", help='LEGACY' action="store", default=1, type=float)
    
                                                                         ^
SyntaxError: invalid syntax
```

**Comment by chenli-bioinfo** [comment]
Thank you very much.

I have added a ',' after help='LEGACY'.
