### ISSUE TITLE
[BUG]mp_feat_norm.txt format wrong: Expected axis has 1 elements, new values have 10 elements

### ISSUE THREAD

**Issue by Elaine-Cheung** [anfoss/PCprophet#9]
**Code**
python3 main.py -sid b/sample_ids.txt -is_ppi False -db coreComplexes.txt 

**Error given in generate_features_v2.py:**
Traceback (most recent call last):
  File "main.py", line 247, in <module>
    main()
  File "main.py", line 221, in main
    [preprocessing(infile, config) for infile in files]
  File "main.py", line 221, in <listcomp>
    [preprocessing(infile, config) for infile in files]
  File "main.py", line 203, in preprocessing
    generate_features.runner(
  File "D:\Documents\PCprophet-1-master\PCprophet\generate_features_v2.py", line 396, in runner
    feat, pks = mp_cmplx(filename=cmplx_comb, goobj=go_tree, gaf=gaf, mult=mult)
  File "D:\Documents\PCprophet-1-master\PCprophet\generate_features_v2.py", line 378, in mp_cmplx
    feats.columns = h
  File "D:\anaconda3\lib\site-packages\pandas\core\generic.py", line 5478, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "D:\anaconda3\lib\site-packages\pandas\core\generic.py", line 670, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "D:\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 220, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 10 elements

**generate_features_v2.py: def mp_cmplx(filename, goobj, gaf, mult)**

During genrating features, 99 out of my total 158 samples data got this error, there is no difference among data format. Without running `h = [ 'ID', 'MB', 'COR', 'SHFT', 'DIF', 'W', 'SC_CC', 'SC_MF', 'SC_BP', 'TOTS']; feats.columns = h`, I could get the mp_feat_norm.txt of the "wrong", and I found that there must be something wrong with `feats = pd.DataFrame(sd.map_partitions(lambda df: process_slice(df, goobj, gaf), meta=(None, 'object')).compute(scheduler='processes').values.tolist())`, results in each row of 'feats' was grouped in one column, they didn't split into ten columns as the "right",  so I guess there's something wrong with "process_slice". After checking the difference between 'right's feats' and 'wrong's feats', I found that after running `feats = ...`, the first row of 'wrong's feats' is none, this may be why split failed. I have proved that after removing the first row of 'feats' input file(cmplx_combined.txt), which caused none in the fisrt row of 'feats', it could run correctly as 'right'. By the way, there's the same error in 'pks'.

I'm not very good at python, finding the cause of the error is the limit for me, so I can not correct the error. I tried clumsy way(if else) to split 'feats' after getting the wrong file, but it didn't work out, it seemd that the change caused high space complexity. Your method is very helpful to me, I hope you can fix this error. Thank you!

**Desktop:**

OS: Windows10
Python version: 3.8.8

**Extract of sample ids file and protein matrix used**
Sorry, I'm not allowed to share this data. This is a 'wrong's cmplx_combined.txt', other files are default, it may help with this problem. 
[cmplx_combined.txt](https://github.com/anfoss/PCprophet/files/7103999/cmplx_combined.txt)

**Comment by anfoss** [comment]
It seems that when I tested parallelization with Dark I used high quality data which always has valid features for every complex. In your case it seems some of them are lower quality and the feature generation does not use them hence returning a nan row. This of course has dimension issues with the rest of the dataframe so led to all sort of errors.

I just pushed a patched version let me know if it works for your case!
